// 
const products = [
{
    id: 1,
    name: "Kui Ye Chen’s AirPods",
    price: 111,
    image:"images/product-1.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur hic minus nihil obcaecati, ratione repellendus saepe sint tenetur totam ullam.",
    category: "Gadgets",
},
{
    id: 2,
    name: "Air Bag",
    price: 121,
    image:"images/product-2.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur hic minus nihil obcaecati, ratione repellendus saepe sint tenetur totam ullam.",
    category: "Bags",
},
{
    id: 3,
    name: "Man’s T-Shirt",
    price: 33,
    image:"images/product-3.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur hic minus nihil obcaecati, ratione repellendus saepe sint tenetur totam ullam.",
    category: "T-Shirt"
},
{
    id: 4,
    name: "Kui Ye Watch",
    price: 222,
    image:"images/product-4.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur hic minus nihil obcaecati, ratione repellendus saepe sint tenetur totam ullam.",
    category: "Watches",
},
{
    id: 5,
    name: "Red Air smartwatch",
    price: 321,
    image:"images/product-5.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur hic minus nihil obcaecati, ratione repellendus saepe sint tenetur totam ullam.",
    category: "Watches",
},
{
    id: 6,
    name: "Nike Air Max 95",
    price: 213,
    image:"images/product-6.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur hic minus nihil obcaecati, ratione repellendus saepe sint tenetur totam ullam.",
    category: "Shoes",
},
{
    id: 7,
    name: "Women prefume",
    price: 44,
    image:"images/product-7.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur hic minus nihil obcaecati, ratione repellendus saepe sint tenetur totam ullam.",
    category: "Cosmetics",
},
{
    id: 8,
    name: "Appl;e Watch",
    price: 55,
    image:"images/product-8.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur hic minus nihil obcaecati, ratione repellendus saepe sint tenetur totam ullam.",
    category: "Watches",
},
{
    id: 9,
    name: "Kui Ye Chen’s Air Gadget",
    price: 321,
    image:"images/product-12.jpg",
    description: "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur hic minus nihil obcaecati, ratione repellendus saepe sint tenetur totam ullam.",
    category: "Gadgets",
},
];
